# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rgcofield/devel/pymoos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rgcofield/devel/pymoos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rgcofield/devel/pymoos/CMakeFiles /home/rgcofield/devel/pymoos/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rgcofield/devel/pymoos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CMOOSCommObject

# Build rule for target.
CMOOSCommObject: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CMOOSCommObject
.PHONY : CMOOSCommObject

# fast build rule for target.
CMOOSCommObject/fast:
	$(MAKE) -f CMakeFiles/CMOOSCommObject.dir/build.make CMakeFiles/CMOOSCommObject.dir/build
.PHONY : CMOOSCommObject/fast

#=============================================================================
# Target rules for targets named CMOOSCommPkt

# Build rule for target.
CMOOSCommPkt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CMOOSCommPkt
.PHONY : CMOOSCommPkt

# fast build rule for target.
CMOOSCommPkt/fast:
	$(MAKE) -f CMakeFiles/CMOOSCommPkt.dir/build.make CMakeFiles/CMOOSCommPkt.dir/build
.PHONY : CMOOSCommPkt/fast

#=============================================================================
# Target rules for targets named CMOOSMsg

# Build rule for target.
CMOOSMsg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CMOOSMsg
.PHONY : CMOOSMsg

# fast build rule for target.
CMOOSMsg/fast:
	$(MAKE) -f CMakeFiles/CMOOSMsg.dir/build.make CMakeFiles/CMOOSMsg.dir/build
.PHONY : CMOOSMsg/fast

#=============================================================================
# Target rules for targets named XPCTcpSocket

# Build rule for target.
XPCTcpSocket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 XPCTcpSocket
.PHONY : XPCTcpSocket

# fast build rule for target.
XPCTcpSocket/fast:
	$(MAKE) -f CMakeFiles/XPCTcpSocket.dir/build.make CMakeFiles/XPCTcpSocket.dir/build
.PHONY : XPCTcpSocket/fast

src/pyMOOSCommObject.o: src/pyMOOSCommObject.cpp.o
.PHONY : src/pyMOOSCommObject.o

# target to build an object file
src/pyMOOSCommObject.cpp.o:
	$(MAKE) -f CMakeFiles/CMOOSCommObject.dir/build.make CMakeFiles/CMOOSCommObject.dir/src/pyMOOSCommObject.cpp.o
.PHONY : src/pyMOOSCommObject.cpp.o

src/pyMOOSCommObject.i: src/pyMOOSCommObject.cpp.i
.PHONY : src/pyMOOSCommObject.i

# target to preprocess a source file
src/pyMOOSCommObject.cpp.i:
	$(MAKE) -f CMakeFiles/CMOOSCommObject.dir/build.make CMakeFiles/CMOOSCommObject.dir/src/pyMOOSCommObject.cpp.i
.PHONY : src/pyMOOSCommObject.cpp.i

src/pyMOOSCommObject.s: src/pyMOOSCommObject.cpp.s
.PHONY : src/pyMOOSCommObject.s

# target to generate assembly for a file
src/pyMOOSCommObject.cpp.s:
	$(MAKE) -f CMakeFiles/CMOOSCommObject.dir/build.make CMakeFiles/CMOOSCommObject.dir/src/pyMOOSCommObject.cpp.s
.PHONY : src/pyMOOSCommObject.cpp.s

src/pyMOOSCommPkt.o: src/pyMOOSCommPkt.cpp.o
.PHONY : src/pyMOOSCommPkt.o

# target to build an object file
src/pyMOOSCommPkt.cpp.o:
	$(MAKE) -f CMakeFiles/CMOOSCommObject.dir/build.make CMakeFiles/CMOOSCommObject.dir/src/pyMOOSCommPkt.cpp.o
	$(MAKE) -f CMakeFiles/CMOOSCommPkt.dir/build.make CMakeFiles/CMOOSCommPkt.dir/src/pyMOOSCommPkt.cpp.o
.PHONY : src/pyMOOSCommPkt.cpp.o

src/pyMOOSCommPkt.i: src/pyMOOSCommPkt.cpp.i
.PHONY : src/pyMOOSCommPkt.i

# target to preprocess a source file
src/pyMOOSCommPkt.cpp.i:
	$(MAKE) -f CMakeFiles/CMOOSCommObject.dir/build.make CMakeFiles/CMOOSCommObject.dir/src/pyMOOSCommPkt.cpp.i
	$(MAKE) -f CMakeFiles/CMOOSCommPkt.dir/build.make CMakeFiles/CMOOSCommPkt.dir/src/pyMOOSCommPkt.cpp.i
.PHONY : src/pyMOOSCommPkt.cpp.i

src/pyMOOSCommPkt.s: src/pyMOOSCommPkt.cpp.s
.PHONY : src/pyMOOSCommPkt.s

# target to generate assembly for a file
src/pyMOOSCommPkt.cpp.s:
	$(MAKE) -f CMakeFiles/CMOOSCommObject.dir/build.make CMakeFiles/CMOOSCommObject.dir/src/pyMOOSCommPkt.cpp.s
	$(MAKE) -f CMakeFiles/CMOOSCommPkt.dir/build.make CMakeFiles/CMOOSCommPkt.dir/src/pyMOOSCommPkt.cpp.s
.PHONY : src/pyMOOSCommPkt.cpp.s

src/pyMOOSMsg.o: src/pyMOOSMsg.cpp.o
.PHONY : src/pyMOOSMsg.o

# target to build an object file
src/pyMOOSMsg.cpp.o:
	$(MAKE) -f CMakeFiles/CMOOSMsg.dir/build.make CMakeFiles/CMOOSMsg.dir/src/pyMOOSMsg.cpp.o
.PHONY : src/pyMOOSMsg.cpp.o

src/pyMOOSMsg.i: src/pyMOOSMsg.cpp.i
.PHONY : src/pyMOOSMsg.i

# target to preprocess a source file
src/pyMOOSMsg.cpp.i:
	$(MAKE) -f CMakeFiles/CMOOSMsg.dir/build.make CMakeFiles/CMOOSMsg.dir/src/pyMOOSMsg.cpp.i
.PHONY : src/pyMOOSMsg.cpp.i

src/pyMOOSMsg.s: src/pyMOOSMsg.cpp.s
.PHONY : src/pyMOOSMsg.s

# target to generate assembly for a file
src/pyMOOSMsg.cpp.s:
	$(MAKE) -f CMakeFiles/CMOOSMsg.dir/build.make CMakeFiles/CMOOSMsg.dir/src/pyMOOSMsg.cpp.s
.PHONY : src/pyMOOSMsg.cpp.s

src/pyXPCTcpSocket.o: src/pyXPCTcpSocket.cpp.o
.PHONY : src/pyXPCTcpSocket.o

# target to build an object file
src/pyXPCTcpSocket.cpp.o:
	$(MAKE) -f CMakeFiles/XPCTcpSocket.dir/build.make CMakeFiles/XPCTcpSocket.dir/src/pyXPCTcpSocket.cpp.o
.PHONY : src/pyXPCTcpSocket.cpp.o

src/pyXPCTcpSocket.i: src/pyXPCTcpSocket.cpp.i
.PHONY : src/pyXPCTcpSocket.i

# target to preprocess a source file
src/pyXPCTcpSocket.cpp.i:
	$(MAKE) -f CMakeFiles/XPCTcpSocket.dir/build.make CMakeFiles/XPCTcpSocket.dir/src/pyXPCTcpSocket.cpp.i
.PHONY : src/pyXPCTcpSocket.cpp.i

src/pyXPCTcpSocket.s: src/pyXPCTcpSocket.cpp.s
.PHONY : src/pyXPCTcpSocket.s

# target to generate assembly for a file
src/pyXPCTcpSocket.cpp.s:
	$(MAKE) -f CMakeFiles/XPCTcpSocket.dir/build.make CMakeFiles/XPCTcpSocket.dir/src/pyXPCTcpSocket.cpp.s
.PHONY : src/pyXPCTcpSocket.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... CMOOSCommObject"
	@echo "... CMOOSCommPkt"
	@echo "... CMOOSMsg"
	@echo "... XPCTcpSocket"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... src/pyMOOSCommObject.o"
	@echo "... src/pyMOOSCommObject.i"
	@echo "... src/pyMOOSCommObject.s"
	@echo "... src/pyMOOSCommPkt.o"
	@echo "... src/pyMOOSCommPkt.i"
	@echo "... src/pyMOOSCommPkt.s"
	@echo "... src/pyMOOSMsg.o"
	@echo "... src/pyMOOSMsg.i"
	@echo "... src/pyMOOSMsg.s"
	@echo "... src/pyXPCTcpSocket.o"
	@echo "... src/pyXPCTcpSocket.i"
	@echo "... src/pyXPCTcpSocket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

